// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

export default{
    mb_28:[
        {
            type:'category', 
            label:'Versions',
            items: [
                'mb_28/Versions/mb_28_v1',
                'mb_28/Versions/mb_28_v2',
                'mb_28/Versions/mb_28_v3',
            ],
        },
        'mb_28/mb_28_installation',
        'mb_28/mb_28_user_guide',
    ],
  mb_trade: [
    {
        type:'category',
        label: 'Versions',
        items: [
            'mb_trade/Versions/mb_trade_v1',
            'mb_trade/Versions/mb_trade_v2',
            'mb_trade/Versions/mb_trade_v3',
        ],  
    },
    'mb_trade/mb_trade_installation',
    'mb_trade/mb_trade_user_guide',
  ],
  fibo_r_28: [
    {
        type:'category', 
        label: 'Versions',
        items: [
            'fibo_r_28/Versions/fibo_r_28_v1',
            'fibo_r_28/Versions/fibo_r_28_v2',
            'fibo_r_28/Versions/fibo_r_28_v3',
        ],
    },
    'fibo_r_28/fibo_r_28_installation',
    'fibo_r_28/fibo_r_28_user_guide',
],
  retracement_28: [
    {
        type:'category', 
        label: 'Versions',
        items: [
            'retracement_28/Versions/retracement_28_v1',
            'retracement_28/Versions/retracement_28_v2',
            'retracement_28/Versions/retracement_28_v3',
        ],
    },
    'retracement_28/retracement_28_installation',
    'retracement_28/retracement_28_user_guide',
],
  retracement_ea: [
    {
        type:'category', 
        label: 'Versions',
        items: [
            'retracement_ea/Versions/retracement_ea_v1',
            'retracement_ea/Versions/retracement_ea_v2',
            'retracement_ea/Versions/retracement_ea_v3',
        ],
    },
    'retracement_ea/retracement_ea_installation',
    'retracement_ea/retracement_ea_user_guide',
],
};

// export default{
//   mb_28:{
//     'MB 28':[
//       {type:'autogenerated', dirName: 'mb_28'},
//     ],
//   },
//   mb_trade:{
//     'MB Trade':[
//       {type:'autogenerated', dirName: 'mb_trade'},
//     ],
//   },
//   fibo_r_28:{
//     'Fibo R 28':[
//       {type:'autogenerated', dirName: 'fibo_r_28'},
//     ],
//   },
//   retracement_28:{
//     'Retracement 28':[
//       {type:'autogenerated', dirName: 'retracement_28'},
//     ],
//   },
//   retracement_ea:{
//     'Retracement EA':[
//       {type:'autogenerated', dirName: 'retracement_ea'},
//     ],
//   },
// };